package com.noahcharlton.wgpuj.jnrgen;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class Config {

    private final File outputDirectory;
    private final String packageName = "com.noahcharlton.wgpuj.jni";
    private final String commentHeader = "/* NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */";

    public Config(File outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    public BufferedWriter startFile(String name) throws IOException {
        File file = outputDirectory.toPath().resolve(name).toFile();

        var writer = new BufferedWriter(new FileWriter(file));
        writer.write("package ");
        writer.write(packageName);
        writer.write(";\n");
        writer.write(commentHeader);
        writer.write("\n");

        return writer;
    }


}
