package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuStencilStateFaceDescriptor extends WgpuJavaStruct {

    private final Enum<WgpuCompareFunction> compare = new Enum<>(WgpuCompareFunction.class);
    private final Enum<WgpuStencilOperation> failOp = new Enum<>(WgpuStencilOperation.class);
    private final Enum<WgpuStencilOperation> depthFailOp = new Enum<>(WgpuStencilOperation.class);
    private final Enum<WgpuStencilOperation> passOp = new Enum<>(WgpuStencilOperation.class);

    private WgpuStencilStateFaceDescriptor(){}

    @Deprecated
    public WgpuStencilStateFaceDescriptor(Runtime runtime){
        super(runtime);
    }

    public static WgpuStencilStateFaceDescriptor createHeap(){
        return new WgpuStencilStateFaceDescriptor();
    }

    public static WgpuStencilStateFaceDescriptor createDirect(){
        var struct = new WgpuStencilStateFaceDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WgpuCompareFunction getCompare(){
        return compare.get();
    }

    public void setCompare(WgpuCompareFunction x){
        this.compare.set(x);
    }

    public WgpuStencilOperation getFailOp(){
        return failOp.get();
    }

    public void setFailOp(WgpuStencilOperation x){
        this.failOp.set(x);
    }

    public WgpuStencilOperation getDepthFailOp(){
        return depthFailOp.get();
    }

    public void setDepthFailOp(WgpuStencilOperation x){
        this.depthFailOp.set(x);
    }

    public WgpuStencilOperation getPassOp(){
        return passOp.get();
    }

    public void setPassOp(WgpuStencilOperation x){
        this.passOp.set(x);
    }

}