package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.WgpuJava;
import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import com.noahcharlton.wgpuj.util.CStrPointer;
import com.noahcharlton.wgpuj.util.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuSwapChainOutput extends WgpuJavaStruct {

    private final Struct.Enum<WgpuSwapChainStatus> status = new Struct.Enum<>(WgpuSwapChainStatus.class);
    private final Struct.Unsigned64 viewId = new Struct.Unsigned64();

    private WgpuSwapChainOutput(){}

    @Deprecated
    public WgpuSwapChainOutput(Runtime runtime){
        super(runtime);
    }

    public static WgpuSwapChainOutput createHeap(){
        return new WgpuSwapChainOutput();
    }

    public static WgpuSwapChainOutput createDirect(){
        var struct = new WgpuSwapChainOutput();
        struct.useDirectMemory();
        return struct;
    }


    public WgpuSwapChainStatus getStatus(){
        return status.get();
    }

    public void setStatus(WgpuSwapChainStatus x){
        this.status.set(x);
    }

    public long getViewId(){
        return viewId.get();
    }

    public void setViewId(long x){
        this.viewId.set(x);
    }

}