package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.WgpuJava;
import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import com.noahcharlton.wgpuj.util.CStrPointer;
import com.noahcharlton.wgpuj.util.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuBufferCopyView extends WgpuJavaStruct {

    private final Struct.Unsigned64 buffer = new Struct.Unsigned64();
    private final WgpuTextureDataLayout layout = inner(WgpuTextureDataLayout.createHeap());

    private WgpuBufferCopyView(){}

    @Deprecated
    public WgpuBufferCopyView(Runtime runtime){
        super(runtime);
    }

    public static WgpuBufferCopyView createHeap(){
        return new WgpuBufferCopyView();
    }

    public static WgpuBufferCopyView createDirect(){
        var struct = new WgpuBufferCopyView();
        struct.useDirectMemory();
        return struct;
    }


    public long getBuffer(){
        return buffer.get();
    }

    public void setBuffer(long x){
        this.buffer.set(x);
    }

    public WgpuTextureDataLayout getLayout(){
        return layout;
    }

}