package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuPipelineLayoutDescriptor extends WgpuJavaStruct {

    private final Struct.Pointer bindGroupLayouts = new Struct.Pointer();
    private final Struct.Unsigned64 bindGroupLayoutsLength = new Struct.Unsigned64();

    private WgpuPipelineLayoutDescriptor(){}

    @Deprecated
    public WgpuPipelineLayoutDescriptor(Runtime runtime){
        super(runtime);
    }

    public static WgpuPipelineLayoutDescriptor createHeap(){
        return new WgpuPipelineLayoutDescriptor();
    }

    public static WgpuPipelineLayoutDescriptor createDirect(){
        var struct = new WgpuPipelineLayoutDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public jnr.ffi.Pointer getBindGroupLayouts(){
        return bindGroupLayouts.get();
    }

    public void setBindGroupLayouts(jnr.ffi.Pointer x){
        this.bindGroupLayouts.set(x);
    }

    public long getBindGroupLayoutsLength(){
        return bindGroupLayoutsLength.get();
    }

    public void setBindGroupLayoutsLength(long x){
        this.bindGroupLayoutsLength.set(x);
    }

}