package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuBindGroupEntry extends WgpuJavaStruct {

    private final Struct.Unsigned32 binding = new Struct.Unsigned32();
    private final Struct.Unsigned32 _NO_USE_padding = new Struct.Unsigned32();
    private final WgpuBindingResource resource = inner(WgpuBindingResource.createHeap());

    private WgpuBindGroupEntry(){}

    @Deprecated
    public WgpuBindGroupEntry(Runtime runtime){
        super(runtime);
    }

    public static WgpuBindGroupEntry createHeap(){
        return new WgpuBindGroupEntry();
    }

    public static WgpuBindGroupEntry createDirect(){
        var struct = new WgpuBindGroupEntry();
        struct.useDirectMemory();
        return struct;
    }


    public long getBinding(){
        return binding.get();
    }

    public void setBinding(long x){
        this.binding.set(x);
    }

    public WgpuBindingResource getResource(){
        return resource;
    }

}