package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.WgpuJava;
import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import com.noahcharlton.wgpuj.util.CStrPointer;
import com.noahcharlton.wgpuj.util.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuComputePipelineDescriptor extends WgpuJavaStruct {

    private final Struct.Unsigned64 layout = new Struct.Unsigned64();
    private final WgpuProgrammableStageDescriptor computeStage = inner(WgpuProgrammableStageDescriptor.createHeap());

    private WgpuComputePipelineDescriptor(){}

    @Deprecated
    public WgpuComputePipelineDescriptor(Runtime runtime){
        super(runtime);
    }

    public static WgpuComputePipelineDescriptor createHeap(){
        return new WgpuComputePipelineDescriptor();
    }

    public static WgpuComputePipelineDescriptor createDirect(){
        var struct = new WgpuComputePipelineDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public long getLayout(){
        return layout.get();
    }

    public void setLayout(long x){
        this.layout.set(x);
    }

    public WgpuProgrammableStageDescriptor getComputeStage(){
        return computeStage;
    }

}