package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuComputePassDescriptor extends WgpuJavaStruct {

    private final Struct.Unsigned32 todo = new Struct.Unsigned32();

    private WgpuComputePassDescriptor(){}

    @Deprecated
    public WgpuComputePassDescriptor(Runtime runtime){
        super(runtime);
    }

    public static WgpuComputePassDescriptor createHeap(){
        return new WgpuComputePassDescriptor();
    }

    public static WgpuComputePassDescriptor createDirect(){
        var struct = new WgpuComputePassDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public long getTodo(){
        return todo.get();
    }

    public void setTodo(long x){
        this.todo.set(x);
    }

}