package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuCommandBufferDescriptor extends WgpuJavaStruct {

    private final Struct.Unsigned32 todo = new Struct.Unsigned32();

    private WgpuCommandBufferDescriptor(){}

    @Deprecated
    public WgpuCommandBufferDescriptor(Runtime runtime){
        super(runtime);
    }

    public static WgpuCommandBufferDescriptor createHeap(){
        return new WgpuCommandBufferDescriptor();
    }

    public static WgpuCommandBufferDescriptor createDirect(){
        var struct = new WgpuCommandBufferDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public long getTodo(){
        return todo.get();
    }

    public void setTodo(long x){
        this.todo.set(x);
    }

}