package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuShaderModuleDescriptor extends WgpuJavaStruct {

    private final WgpuU32Array code = inner(WgpuU32Array.createHeap());

    private WgpuShaderModuleDescriptor(){}

    @Deprecated
    public WgpuShaderModuleDescriptor(Runtime runtime){
        super(runtime);
    }

    public static WgpuShaderModuleDescriptor createHeap(){
        return new WgpuShaderModuleDescriptor();
    }

    public static WgpuShaderModuleDescriptor createDirect(){
        var struct = new WgpuShaderModuleDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WgpuU32Array getCode(){
        return code;
    }

}